name: Gurobify
version: 2.0.0
date: 24/06/2021
description: A GAP interface to Gurobi Optimizer.

authors:
    - name: Jesse Lansdown
      url: https://www.jesselansdown.com

maintainers:
    - name: Jesse Lansdown
      url: https://www.jesselansdown.com

GAP: ">= 4.8"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.4"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://www.jesselansdown.com/Gurobify
readme: README.md
packageinfo: https://www.jesselansdown.com/Gurobify/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://zenodo.org/record/5025558/files/Gurobify-2.0.0.tar.gz?download=1

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
